Hometask1
AndriiBakayev/EPAM-PHP-Tasks pull request #3
Opened 2022-08-10 01:53 UTC by AndriiBakayev

Added Basics.php and BasicValidation.php with PSR12 requirements

2022-08-10 11:22 UTC, yderevianko-cartera requested changes

2022-08-10 11:22 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +            echo("Hello $minute \n");
please fix nuber of spaces, should be 8 for line 23-24

2022-08-10 11:22 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +        } elseif ($minute <= 60) {
in validator you have $minute > 59 throw exception but you check for $minute <= 60

2022-08-10 11:22 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +    public function isLeapYear(int $year): bool
please add annotations

2022-08-10 11:22 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +    public function isSumEqual(string $input): bool
please add annotations

2022-08-10 11:22 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +            return (false);
please remove () from true and false

2022-08-10 11:22 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +            return (true);
please remove () from true and false

2022-08-10 11:22 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +        if ((int)substr($input, 0, 1) + (int)substr($input, 1, 1) + (int)substr($input, 2, 1) == (int)substr($input, 3, 1) + (int)substr($input, 4, 1) + (int)substr($input, 5, 1)) {
please use === instaed of ==
also you can works with strings as with arrays

2022-08-12 15:44 UTC, AndriiBakayev commented
Closed due error corrections

2022-08-15 07:11 UTC, yderevianko-cartera commented
@AndriiBakayev Please do not close pull requests. Just commit and push changes and it will automatically update pull request

2022-08-16 19:06 UTC, AndriiBakayev commented
commited new chandes and reopened pull request

2022-08-17 07:10 UTC, yderevianko-cartera requested changes

2022-08-17 07:10 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +    private mixed $_validator;
please use camelCase name convention and the type of it should be BasicsValidatorInterface instead of mixed

2022-08-17 07:10 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +        if ((int)$input[0]+(int)$input[1]+(int)$input[2]===(int)substr($input, 3, 1) +(int)substr($input, 4, 1) +(int)substr($input, 5, 1)
please read PSR standarts

2022-08-17 07:10 UTC, yderevianko-cartera commented on src/basics/BasicsValidator.php
> +integers in range 0-59. Input was: ' . $minute
should be single line message

2022-08-17 07:10 UTC, yderevianko-cartera commented on src/basics/BasicsValidator.php
> +integers in range 1900-9999. Input was: ' . $year
should be single line message

2022-08-17 07:10 UTC, yderevianko-cartera commented on src/basics/BasicsValidator.php
> +strings with numbers strlen()=6. Input was: ' . $input
should be single line message

2022-08-17 07:10 UTC, yderevianko-cartera commented on src/basics/BasicsValidator.php
> +            || strlen($input) != 6
should be single line message

2022-08-17 07:10 UTC, yderevianko-cartera commented on src/basics/BasicsValidator.php
> +            || strlen($input) != 6
please always use strict checks (!==)

2022-08-18 11:48 UTC, yderevianko-cartera requested changes

2022-08-18 11:48 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +            : ($minute <= 15 ? 'first'
please use if else instead of ?:
it is only usfull if you have 2 or maximum 3 checks

2022-08-18 12:16 UTC, yderevianko-cartera commented on src/basics/BasicsValidator.php
> +            ! is_string($input)
should be !is_string

2022-08-18 14:28 UTC, yderevianko-cartera approved these changes

2022-08-22 08:56 UTC, yderevianko-cartera requested changes

2022-08-22 08:56 UTC, yderevianko-cartera commented on src/basics/Basics.php
> +        return $input[0] + $input[1] + $input[2] === $input[3] + $input[4] + $input[5];
plaese add empty line before return

2022-08-22 08:56 UTC, yderevianko-cartera commented on src/basics/BasicsValidator.php
> +            !is_int($year)
can be in single line
if (!is_int($year) || $year < 1900 || $year > 9999) {

2022-08-22 08:56 UTC, yderevianko-cartera commented on src/basics/BasicsValidator.php
> +            !is_string($input)
can be in single line

2022-08-22 08:56 UTC, yderevianko-cartera commented on src/basics/BasicsValidator.php
> +                . ' with numbers strlen()=6. Input was: '
can be in single line

2022-08-22 08:56 UTC, yderevianko-cartera commented on src/basics/BasicsValidator.php
> +                . ' in range 1900-9999. Input was: '
can be in single line

2022-08-23 07:22 UTC, yderevianko-cartera approved these changes

2022-08-28 19:44 UTC, merged